import { useState } from "react";
import { markLessonRead, type StudyProgress } from "../data/progress";

type Props={onRead:(progress:StudyProgress)=>void;onExit:()=>void};

export default function Lesson({onRead,onExit}:Props){
 const [confirmed,setConfirmed]=useState(false);
 const complete=()=>{const progress=markLessonRead();setConfirmed(true);setTimeout(()=>onRead(progress),250);};
 return <div className="content"><div className="lesson-header"><div><span className="badge">DAILY BIOLOGY LESSON</span><h2>Cellular Energy & ATP</h2><p>Read this lesson before attempting today's RAT.</p></div><button className="secondary-button" onClick={onExit}>Back to dashboard</button></div><article className="lesson-card"><section><span className="eyebrow">01 • Core concept</span><h3>Why cells need ATP</h3><p>Cells constantly perform work: moving substances across membranes, building molecules, transmitting signals and powering muscle contraction. ATP acts as the immediate energy currency used to couple energy-releasing reactions to energy-demanding cellular work.</p></section><section><span className="eyebrow">02 • Production</span><h3>Where ATP comes from</h3><p>Most ATP in aerobic human cells is produced through cellular respiration. Glycolysis occurs in the cytosol, while the citric acid cycle and oxidative phosphorylation occur in mitochondria. Oxidative phosphorylation generates the largest share of ATP under typical aerobic conditions.</p></section><section><span className="eyebrow">03 • High-yield point</span><h3>Remember this for the RAT</h3><div className="high-yield"><strong>ATP links metabolism to cellular work.</strong><span>The mitochondrion is central to aerobic ATP production, but glycolysis itself takes place in the cytosol.</span></div></section><section><span className="eyebrow">04 • Quick check</span><h3>What should you be able to explain?</h3><ul><li>Why ATP is used as an immediate energy carrier.</li><li>Where glycolysis, the citric acid cycle and oxidative phosphorylation occur.</li><li>Why oxygen availability affects aerobic ATP production.</li></ul></section></article><div className="lesson-complete"><div><strong>Lesson complete?</strong><span>Once you finish reading, unlock today's 10-question RAT.</span></div><button className="primary-button" disabled={confirmed} onClick={complete}>{confirmed?"RAT UNLOCKED":"Finish lesson • Take today's RAT"}</button></div></div>;
}