import { useEffect, useMemo, useRef, useState } from "react";
import { ASSESSMENT_CONFIG } from "../data/testConfig";
import { setCloudUpdatedAt } from "../data/account";
import { backendEnabled, claimAssessmentSession, submitAssessment } from "../data/api";
import { questions, type Question, getQuestionsForLesson } from "../data/questions";
import type { CurriculumTrack } from "../data/curriculum";
import type { SchoolForm } from "../data/schoolForm";
import { selectRATQuestions } from "../data/questionSelector";
import { clearActiveRAT, getActiveRAT, getProgress, getTodaysLessonId, hasCompletedRATToday, hasReadLessonToday, hydrateQuestions, recordRATAttempt, saveActiveRAT, type StudyProgress } from "../data/progress";
type Props={curriculum:CurriculumTrack;schoolForm:SchoolForm;onExit:()=>void;onProgress:(progress:StudyProgress)=>void;onLesson:()=>void};

export default function RAT({curriculum,schoolForm,onExit,onProgress,onLesson}:Props){
 const config=ASSESSMENT_CONFIG.rat, progress=getProgress(), todaysLessonId=getTodaysLessonId(curriculum,schoolForm), readToday=hasReadLessonToday(progress,todaysLessonId), completedToday=hasCompletedRATToday(progress);
 const lessonQuestions=readToday ? getQuestionsForLesson(todaysLessonId,curriculum) as Question[] : [];
 const recentAssessmentIds=progress.attempts.flatMap(a=>a.questionIds??[]);
 const saved=getActiveRAT(), restored=saved?hydrateQuestions(saved,questions):[];
 const initialSessionId=saved?.sessionId??crypto.randomUUID();
 const optionOrderByQuestion = useRef<Record<string, number[]>>({});
 const randomizeOptionsForSession=(items:Question[],seed:string):Question[]=>items.map(question=>{
  const chars=Array.from(seed+question.id);
  let hash=2166136261;
  for(const char of chars) hash=Math.imul(hash^char.charCodeAt(0),16777619);
  const order=[0,1,2];
  for(let i=order.length-1;i>0;i--){hash=Math.imul(hash^i,16777619);const j=Math.abs(hash)% (i+1);[order[i],order[j]]=[order[j],order[i]];}
  optionOrderByQuestion.current[question.id]=order;
  return {...question,options:order.map(index=>question.options[index]) as [string,string,string],answer:order.findIndex(index=>index===question.answer)};
 });
 const baseQuestions=restored.length===config.questionCount && restored.every(q=>lessonQuestions.some(item=>item.id===q.id))?restored:selectRATQuestions(lessonQuestions,config.questionCount,recentAssessmentIds);
 const [sessionId,setSessionId]=useState(initialSessionId);
 const [testQuestions,setTestQuestions]=useState<Question[]>(()=>randomizeOptionsForSession(baseQuestions,initialSessionId));
 const [current,setCurrent]=useState(saved&&restored.length===config.questionCount?saved.current:0);
 const [answers,setAnswers]=useState<Record<string,number>>(saved&&restored.length===config.questionCount?saved.answers:{});
 const [secondsLeft,setSecondsLeft]=useState(saved&&restored.length===config.questionCount?saved.secondsLeft:config.durationSeconds);
 const [submitted,setSubmitted]=useState(false),[finished,setFinished]=useState(false),[claiming,setClaiming]=useState(backendEnabled()),[serverCompletedToday,setServerCompletedToday]=useState(false),[claimError,setClaimError]=useState<string|null>(null);
 useEffect(()=>{  if(!backendEnabled()||!testQuestions.length||serverCompletedToday)return;  let cancelled=false;  setClaiming(true);setClaimError(null);  claimAssessmentSession("RAT",sessionId,testQuestions.map(item=>item.id)).then(response=>{    if(cancelled)return;    if(response.sessionId&&response.sessionId!==sessionId)setSessionId(response.sessionId);    if(response.questionIds?.length){      const issued=hydrateQuestions({questionIds:response.questionIds,current:0,answers:{},secondsLeft:config.durationSeconds,startedAt:new Date().toISOString()},questions);      if(issued.length===config.questionCount)setTestQuestions(randomizeOptionsForSession(issued,response.sessionId||sessionId));    }  }).catch(error=>{    if(cancelled)return;    const message=error instanceof Error?error.message:"Unable to secure today's RAT.";    if(message.toLowerCase().includes("today's rat")||message.toLowerCase().includes("already been completed"))setServerCompletedToday(true);    else setClaimError(message);  }).finally(()=>{if(!cancelled)setClaiming(false);});  return()=>{cancelled=true}; },[]);
 const finish=async()=>{if(finished)return;setFinished(true);let verified={correct:testQuestions.filter(item=>answers[item.id]===item.answer).length,score:0,accuracy:0,passed:false,correctQuestionIds:testQuestions.filter(item=>answers[item.id]===item.answer).map(item=>item.id),missedQuestionIds:testQuestions.filter(item=>answers[item.id]!==item.answer).map(item=>item.id)};verified.score=verified.correct*config.pointsPerCorrect;verified.accuracy=Math.round(verified.correct/testQuestions.length*100);verified.passed=verified.accuracy>=config.passmark;if(backendEnabled()&&sessionId){try{const serverAnswers:Record<string,number>={};for(const item of testQuestions){const selected=answers[item.id];const order=optionOrderByQuestion.current[item.id];if(selected!==undefined&&order&&order[selected]!==undefined)serverAnswers[item.id]=order[selected];}const response=await submitAssessment("RAT",sessionId,testQuestions.map(item=>item.id),serverAnswers);setCloudUpdatedAt(response.updatedAt);verified=response.result;}catch(error){setFinished(false);const reason=error instanceof Error?error.message:"Unknown submission error";window.alert(`RAT submission could not be verified: ${reason}. Please check your connection and try again.`);return;}}const p=recordRATAttempt({score:verified.score,correct:verified.correct,total:testQuestions.length,accuracy:verified.accuracy,passed:verified.passed,questionIds:testQuestions.map(item=>item.id),correctQuestionIds:verified.correctQuestionIds},verified.missedQuestionIds,sessionId);clearActiveRAT();onProgress(p);setSubmitted(true);};
 useEffect(()=>{if(submitted||!readToday||completedToday)return;const timer=window.setInterval(()=>setSecondsLeft(v=>{if(v<=1){window.clearInterval(timer);setSecondsLeft(0);return 0;}return v-1;}),1000);return()=>window.clearInterval(timer);},[submitted,readToday,completedToday]);
 useEffect(()=>{if(!submitted&&readToday&&!completedToday&&secondsLeft===0)finish();},[secondsLeft,submitted,readToday,completedToday]);
 useEffect(()=>{if(submitted||!readToday||completedToday)return;saveActiveRAT({sessionId,questionIds:testQuestions.map(q=>q.id),current,answers,secondsLeft,startedAt:saved?.startedAt??new Date().toISOString()});},[answers,current,secondsLeft,submitted,testQuestions,saved?.startedAt,readToday,completedToday,sessionId]);
 const score=useMemo(()=>testQuestions.reduce((t,item)=>t+(answers[item.id]===item.answer?config.pointsPerCorrect:0),0),[answers,testQuestions,config.pointsPerCorrect]);
 const minutes=Math.floor(secondsLeft/60).toString().padStart(2,"0"),seconds=(secondsLeft%60).toString().padStart(2,"0");
 if(readToday && lessonQuestions.length<config.questionCount)return <div className="content"><div className="empty-state"><span className="badge warning">QUESTION BANK</span><h2>Today&apos;s RAT is not ready</h2><p>This lesson does not yet have enough questions for the scheduled RAT. Add more questions to this lesson before attempting it.</p><button className="secondary-button" onClick={onExit}>Back to dashboard</button></div></div>;
 if(!readToday)return <div className="content"><div className="empty-state"><span className="badge warning">LESSON REQUIRED</span><h2>Read today&apos;s lesson first</h2><p>The daily RAT is locked until you reach 100% reading progress in TODAY&apos;S LESSON. The only unlock path is the TAKE RAT button at the end of the completed lesson.</p><button className="primary-button" onClick={onLesson}>Open TODAY&apos;S LESSON</button></div></div>;
 if(claiming&&!serverCompletedToday&&!submitted)return <div className="content"><div className="empty-state"><span className="badge">SECURING RAT</span><h2>Preparing today&apos;s RAT...</h2><p>This RAT is being locked to your account for today. You cannot receive another RAT until tomorrow.</p></div></div>;
 if(claimError&&!submitted)return <div className="content"><div className="empty-state"><span className="badge warning">RAT SECURITY ERROR</span><h2>Today&apos;s RAT could not be secured</h2><p>{claimError}</p><button className="primary-button" onClick={()=>window.location.reload()}>Try again</button><button className="secondary-button" onClick={onExit}>Back to dashboard</button></div></div>;
 if((completedToday||serverCompletedToday)&&!submitted)return <div className="content"><div className="empty-state"><span className="badge success">RAT COMPLETED</span><h2>Today&apos;s RAT is already done</h2><p>You can only take the scheduled RAT once per day. If you left the results screen, the retake is no longer available. Incorrect questions have been moved to Revision.</p><button className="primary-button" onClick={onExit}>Back to dashboard</button></div></div>;
 if(submitted){const correct=testQuestions.filter(item=>answers[item.id]===item.answer).length;const accuracy=Math.round(correct/testQuestions.length*100);return <div className="content"><div className="result-card"><span className={accuracy>=config.passmark?"badge success":"badge warning"}>{accuracy>=config.passmark?"RAT PASSED":"RAT REVIEW"}</span><h2>{score} / {config.questionCount*config.pointsPerCorrect} points</h2><p>You answered {correct} of {testQuestions.length} questions correctly. Review the explanations below before moving to Revision.</p><div className="result-grid"><div><strong>{correct}</strong><span>Correct</span></div><div><strong>{testQuestions.length-correct}</strong><span>Incorrect</span></div><div><strong>{accuracy}%</strong><span>Accuracy</span></div></div><div className="review-list"><h3>Missed questions • Review</h3>{testQuestions.filter(item=>answers[item.id]!==item.answer).map(item=><article key={item.id} className="review-item"><strong>{item.prompt}</strong><p><b>Correct answer:</b> {item.options[item.answer]}</p><p>{item.explanation}</p><small>{item.reference}</small></article>)}{testQuestions.every(item=>answers[item.id]===item.answer)&&<p className="review-empty">Perfect score. No missed questions to review.</p>}</div><div className="result-actions"><button className="secondary-button" onClick={onExit}>Leave results</button></div></div></div>;}
 const question=testQuestions[current],answered=Object.keys(answers).length;
 return <div className="content"><div className="test-header"><div><span className="eyebrow">Readiness Assessment Test</span><h2>Daily RAT</h2><p>{config.questionCount} questions • 10 minutes • {config.pointsPerCorrect} points per correct answer • Passmark {config.passmark}%</p></div><div className={secondsLeft<=60?"timer danger":"timer"}>{minutes}:{seconds}</div></div><div className="question-layout"><div className="question-card"><div className="question-meta"><span>Question {current+1} of {testQuestions.length}</span><span>{question.topic} • {question.difficulty}</span></div><h3>{question.prompt}</h3><div className="options">{question.options.map((option,index)=><button key={option} className={answers[question.id]===index?"option selected":"option"} onClick={()=>setAnswers(old=>({...old,[question.id]:index}))}><span>{String.fromCharCode(65+index)}</span>{option}</button>)}</div><div className="question-actions"><button className="secondary-button" disabled={current===0} onClick={()=>setCurrent(v=>v-1)}>Previous</button>{current<testQuestions.length-1?<button className="primary-button" onClick={()=>setCurrent(v=>v+1)}>Next</button>:<button className="primary-button" onClick={finish}>Submit RAT</button>}</div></div><aside className="question-map"><strong>Progress</strong><span>{answered} / {testQuestions.length} answered</span><div className="map-grid">{testQuestions.map((item,index)=><button key={item.id} className={answers[item.id]!==undefined?"map-dot answered":"map-dot"} onClick={()=>setCurrent(index)}>{index+1}</button>)}</div><small>Your answers and timer are saved automatically. One RAT is allowed per day.</small></aside></div></div>;
}
