import { useEffect, useMemo, useState } from "react";
import { ASSESSMENT_CONFIG } from "../data/testConfig";
import { questions, shuffleQuestions, type Question } from "../data/questions";
import { canUseRATRetakeToday, clearActiveRAT, consumeRATRetake, getActiveRAT, getProgress, hasCompletedRATToday, hasReadLessonToday, hydrateQuestions, recordRATAttempt, saveActiveRAT, type StudyProgress } from "../data/progress";
type Props={onExit:()=>void;onProgress:(progress:StudyProgress)=>void;onLesson:()=>void};

export default function RAT({onExit,onProgress,onLesson}:Props){
 const config=ASSESSMENT_CONFIG.rat, progress=getProgress(), readToday=hasReadLessonToday(progress), completedToday=hasCompletedRATToday(progress);
 const lessonQuestions=questions.filter(q=>q.lessonId===progress.lessonReadId);
 const saved=getActiveRAT(), restored=saved?hydrateQuestions(saved,questions):[];
 const [testQuestions,setTestQuestions]=useState<Question[]>(restored.length===config.questionCount?restored:()=>shuffleQuestions(lessonQuestions,config.questionCount));
 const [current,setCurrent]=useState(saved&&restored.length===config.questionCount?saved.current:0);
 const [answers,setAnswers]=useState<Record<string,number>>(saved&&restored.length===config.questionCount?saved.answers:{});
 const [secondsLeft,setSecondsLeft]=useState(saved&&restored.length===config.questionCount?saved.secondsLeft:config.durationSeconds);
 const [submitted,setSubmitted]=useState(false),[finished,setFinished]=useState(false),[retakeUsed,setRetakeUsed]=useState(false),[retakeActive,setRetakeActive]=useState(false);
 const finish=()=>{if(finished)return;setFinished(true);const correct=testQuestions.filter(item=>answers[item.id]===item.answer).length;const score=correct*config.pointsPerCorrect;const accuracy=Math.round(correct/testQuestions.length*100);const p=recordRATAttempt({score,correct,total:testQuestions.length,accuracy,passed:accuracy>=config.passmark},testQuestions.filter(item=>answers[item.id]!==item.answer).map(item=>item.id));clearActiveRAT();onProgress(p);setSubmitted(true);};
 useEffect(()=>{if(submitted||!readToday||(completedToday&&!retakeActive))return;const timer=window.setInterval(()=>setSecondsLeft(v=>{if(v<=1){window.clearInterval(timer);setSecondsLeft(0);return 0;}return v-1;}),1000);return()=>window.clearInterval(timer);},[submitted,readToday,completedToday,retakeActive]);
 useEffect(()=>{if(!submitted&&readToday&&!completedToday&&secondsLeft===0)finish();},[secondsLeft,submitted,readToday,completedToday]);
 useEffect(()=>{if(submitted||!readToday||completedToday)return;saveActiveRAT({questionIds:testQuestions.map(q=>q.id),current,answers,secondsLeft,startedAt:saved?.startedAt??new Date().toISOString()});},[answers,current,secondsLeft,submitted,testQuestions,saved?.startedAt,readToday,completedToday]);
 const score=useMemo(()=>testQuestions.reduce((t,item)=>t+(answers[item.id]===item.answer?config.pointsPerCorrect:0),0),[answers,testQuestions,config.pointsPerCorrect]);
 const minutes=Math.floor(secondsLeft/60).toString().padStart(2,"0"),seconds=(secondsLeft%60).toString().padStart(2,"0");
 if(readToday && lessonQuestions.length<config.questionCount)return <div className="content"><div className="empty-state"><span className="badge warning">QUESTION BANK</span><h2>Today&apos;s RAT is not ready</h2><p>This lesson does not yet have enough questions for the scheduled RAT. Add more questions to this lesson before attempting it.</p><button className="secondary-button" onClick={onExit}>Back to dashboard</button></div></div>;
 if(!readToday)return <div className="content"><div className="empty-state"><span className="badge warning">LESSON REQUIRED</span><h2>Read today&apos;s lesson first</h2><p>The daily RAT is locked until you reach 100% reading progress in TODAY&apos;S LESSON. The only unlock path is the TAKE RAT button at the end of the completed lesson.</p><button className="primary-button" onClick={onLesson}>Open TODAY&apos;S LESSON</button></div></div>;
 if(completedToday&&!submitted&&!retakeActive)return <div className="content"><div className="empty-state"><span className="badge success">RAT COMPLETED</span><h2>Today&apos;s RAT is already done</h2><p>You can only take the scheduled RAT once per day. If you left the results screen, the retake is no longer available. Incorrect questions have been moved to Revision.</p><button className="primary-button" onClick={onExit}>Back to dashboard</button></div></div>;
 if(submitted){const correct=testQuestions.filter(item=>answers[item.id]===item.answer).length;const accuracy=Math.round(correct/testQuestions.length*100);const canRetake=canUseRATRetakeToday(getProgress())&&!retakeUsed;return <div className="content"><div className="result-card"><span className={accuracy>=config.passmark?"badge success":"badge warning"}>{accuracy>=config.passmark?"RAT PASSED":"RAT REVIEW"}</span><h2>{score} / {config.questionCount*config.pointsPerCorrect} points</h2><p>You answered {correct} of {testQuestions.length} questions correctly. Review the explanations below before moving to Revision.</p><div className="result-grid"><div><strong>{correct}</strong><span>Correct</span></div><div><strong>{testQuestions.length-correct}</strong><span>Incorrect</span></div><div><strong>{accuracy}%</strong><span>Accuracy</span></div></div><div className="review-list"><h3>Missed questions • Review</h3>{testQuestions.filter(item=>answers[item.id]!==item.answer).map(item=><article key={item.id} className="review-item"><strong>{item.prompt}</strong><p><b>Correct answer:</b> {item.options[item.answer]}</p><p>{item.explanation}</p><small>{item.reference}</small></article>)}{testQuestions.every(item=>answers[item.id]===item.answer)&&<p className="review-empty">Perfect score. No missed questions to review.</p>}</div><div className="result-actions"><button className="secondary-button" onClick={onExit}>Leave results</button>{canRetake&&<button className="primary-button" onClick={()=>{consumeRATRetake();setRetakeUsed(true);setRetakeActive(true);setTestQuestions(shuffleQuestions(lessonQuestions,config.questionCount));setCurrent(0);setAnswers({});setSecondsLeft(config.durationSeconds);setSubmitted(false);setFinished(false);}}>Retake RAT</button>}</div></div></div>;}
 const question=testQuestions[current],answered=Object.keys(answers).length;
 return <div className="content"><div className="test-header"><div><span className="eyebrow">Readiness Assessment Test</span><h2>Daily RAT</h2><p>{config.questionCount} questions • 15 minutes • {config.pointsPerCorrect} points per correct answer • Passmark {config.passmark}%</p></div><div className={secondsLeft<=60?"timer danger":"timer"}>{minutes}:{seconds}</div></div><div className="question-layout"><div className="question-card"><div className="question-meta"><span>Question {current+1} of {testQuestions.length}</span><span>{question.topic} • {question.difficulty}</span></div><h3>{question.prompt}</h3><div className="options">{question.options.map((option,index)=><button key={option} className={answers[question.id]===index?"option selected":"option"} onClick={()=>setAnswers(old=>({...old,[question.id]:index}))}><span>{String.fromCharCode(65+index)}</span>{option}</button>)}</div><div className="question-actions"><button className="secondary-button" disabled={current===0} onClick={()=>setCurrent(v=>v-1)}>Previous</button>{current<testQuestions.length-1?<button className="primary-button" onClick={()=>setCurrent(v=>v+1)}>Next</button>:<button className="primary-button" onClick={finish}>Submit RAT</button>}</div></div><aside className="question-map"><strong>Progress</strong><span>{answered} / {testQuestions.length} answered</span><div className="map-grid">{testQuestions.map((item,index)=><button key={item.id} className={answers[item.id]!==undefined?"map-dot answered":"map-dot"} onClick={()=>setCurrent(index)}>{index+1}</button>)}</div><small>Your answers and timer are saved automatically. Retake is available only while you remain on the result screen.</small></aside></div></div>;
}
