import { useEffect, useState } from "react";
import { questions, type Question } from "../data/questions";
import { clearActiveRevision, getActiveRevision, getProgress, hydrateQuestions, recordRevisionAttempt, saveActiveRevision, type StudyProgress } from "../data/progress";

type Props={onExit:()=>void;onProgress:(p:StudyProgress)=>void};

export default function Revision({onExit,onProgress}:Props){
 const progress=getProgress(), missed=questions.filter(q=>progress.missedQuestionIds.includes(q.id));
 const saved=getActiveRevision(), restored=saved?hydrateQuestions(saved,questions):[];
 const [mode,setMode]=useState<"review"|"redo">(restored.length?"redo":"review");
 const [items,setItems]=useState<Question[]>(restored.length?restored:missed);
 const [current,setCurrent]=useState(saved?.current??0),[answers,setAnswers]=useState<Record<string,number>>(saved?.answers??{}),[submitted,setSubmitted]=useState(false);
 useEffect(()=>{if(mode==="redo"&&!submitted)saveActiveRevision({questionIds:items.map(q=>q.id),current,answers,startedAt:saved?.startedAt??new Date().toISOString()});},[mode,submitted,items,current,answers,saved?.startedAt]);
 if(mode==="review") return <div className="content"><div className="test-header"><div><span className="eyebrow">Targeted Revision</span><h2>Review missed questions</h2><p>{missed.length} question{missed.length===1?"":"s"} in your revision queue.</p></div></div>{missed.length===0?<div className="empty-state"><span className="badge success">ALL CLEAR</span><h2>No missed questions</h2><p>Incorrect answers from future RATs and CATs will automatically appear here with their explanations.</p><button className="secondary-button" onClick={onExit}>Back to dashboard</button></div>:<><div className="revision-list">{missed.map((q,i)=><article className="panel revision-item" key={q.id}><div className="question-meta"><span>Revision {i+1}</span><span>{q.topic} • {q.difficulty}</span></div><h3>{q.prompt}</h3><div className="revision-answer"><strong>Correct answer: {String.fromCharCode(65+q.answer)}. {q.options[q.answer]}</strong><p>{q.explanation}</p><small>Reference: {q.reference}</small></div></article>)}</div><div className="result-actions"><button className="secondary-button" onClick={onExit}>Back</button><button className="primary-button" onClick={()=>{setItems(missed);setCurrent(0);setAnswers({});setSubmitted(false);setMode("redo");}}>Redo revised questions • +2 pts each</button></div></>}</div>;
 if(!items.length)return <div className="content"><div className="empty-state"><h2>No revision questions</h2><button className="secondary-button" onClick={onExit}>Back</button></div></div>;
 const finish=()=>{const correct=items.filter(q=>answers[q.id]===q.answer).length;const p=recordRevisionAttempt({score:correct*2,correct,total:items.length,accuracy:Math.round(correct/items.length*100),questionIds:items.map(q=>q.id)},items.filter(q=>answers[q.id]===q.answer).map(q=>q.id));clearActiveRevision();onProgress(p);setSubmitted(true);};
 if(submitted){const correct=items.filter(q=>answers[q.id]===q.answer).length;return <div className="content"><div className="result-card"><span className="badge success">REVISION COMPLETE</span><h2>+{correct*2} bonus points</h2><p>{correct} of {items.length} revised questions were correct.</p><div className="result-grid"><div><strong>{correct}</strong><span>Correct</span></div><div><strong>{items.length-correct}</strong><span>Still to revise</span></div><div><strong>{Math.round(correct/items.length*100)}%</strong><span>Accuracy</span></div></div><div className="result-actions"><button className="secondary-button" onClick={onExit}>Back to dashboard</button><button className="primary-button" onClick={()=>{const fresh=getProgress();const remaining=questions.filter(q=>fresh.missedQuestionIds.includes(q.id));setItems(remaining);setCurrent(0);setAnswers({});setSubmitted(false);setMode("review");}}>Review remaining</button></div></div></div>;}
 const q=items[current];
 return <div className="content"><div className="test-header"><div><span className="eyebrow">Bonus Revision</span><h2>Redo missed questions</h2><p>Earn <strong>2 bonus points</strong> for every correctly answered revised question.</p></div><span className="badge">+2 EACH</span></div><div className="question-layout"><div className="question-card"><div className="question-meta"><span>Question {current+1} of {items.length}</span><span>{q.topic} • {q.difficulty}</span></div><h3>{q.prompt}</h3><div className="options">{q.options.map((o,i)=><button key={o} className={answers[q.id]===i?"option selected":"option"} onClick={()=>setAnswers(old=>({...old,[q.id]:i}))}><span>{String.fromCharCode(65+i)}</span>{o}</button>)}</div><div className="question-actions"><button className="secondary-button" disabled={!current} onClick={()=>setCurrent(v=>v-1)}>Previous</button>{current<items.length-1?<button className="primary-button" onClick={()=>setCurrent(v=>v+1)}>Next</button>:<button className="primary-button" onClick={finish}>Submit Revision</button>}</div></div><aside className="question-map"><strong>Revision progress</strong><span>{Object.keys(answers).length} / {items.length} answered</span><div className="map-grid">{items.map((item,i)=><button key={item.id} className={answers[item.id]!==undefined?"map-dot answered":"map-dot"} onClick={()=>setCurrent(i)}>{i+1}</button>)}</div><small>Correctly redone questions leave the queue. Incorrect ones remain for another revision round.</small></aside></div></div>;
}
