import { useEffect, useMemo, useState, type CSSProperties } from "react";
import RAT from "./pages/RAT";
import CAT from "./pages/CAT";
import Revision from "./pages/Revision";
import Practice from "./pages/Practice";
import Lesson from "./pages/Lesson";
import Analytics from "./pages/Analytics";
import { getProgress, hasCompletedRATToday, hasReadLessonToday, type StudyProgress } from "./data/progress";
import { getDailyFact } from "./data/commonKnowledge";

type Section="Dashboard"|"Lesson"|"RAT"|"CAT"|"Practice"|"Revision"|"Analytics"|"Calendar"|"Settings";
const sections:Section[]=["Dashboard","Lesson","RAT","CAT","Practice","Revision","Analytics","Calendar","Settings"];
const icons:Record<Section,string>={Dashboard:"⌂",Lesson:"01",RAT:"02",CAT:"03",Practice:"04",Revision:"05",Analytics:"06",Calendar:"07",Settings:"08"};

function App(){
 const [active,setActive]=useState<Section>("Dashboard"),[dark,setDark]=useState(true),[time,setTime]=useState(new Date()),[progress,setProgress]=useState<StudyProgress>(()=>getProgress()),[isFullscreen,setIsFullscreen]=useState(false),[celebration,setCelebration]=useState<string|null>(null);
 useEffect(()=>{const timer=window.setInterval(()=>setTime(new Date()),1000);return()=>window.clearInterval(timer);},[]);
 useEffect(()=>{document.documentElement.dataset.theme=dark?"dark":"light";},[dark]);
 useEffect(()=>{const sync=()=>setIsFullscreen(Boolean(document.fullscreenElement));document.addEventListener("fullscreenchange",sync);return()=>document.removeEventListener("fullscreenchange",sync);},[]);
 const toggleFullscreen=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{}};
 const completeTask=(next:StudyProgress,message:string)=>{setProgress(next);setCelebration(message);window.setTimeout(()=>setCelebration(null),2800);};
 const greeting=useMemo(()=>{const h=time.getHours();return h<12?"Good Morning":h<17?"Good Afternoon":h<21?"Good Evening":"Good Night";},[time]);
 const dailyFact=useMemo(()=>getDailyFact(time),[time]);
 const [typedFact,setTypedFact]=useState("");
 useEffect(()=>{setTypedFact("");let index=0;const timer=window.setInterval(()=>{index+=1;setTypedFact(dailyFact.fact.slice(0,index));if(index>=dailyFact.fact.length)window.clearInterval(timer);},28);return()=>window.clearInterval(timer);},[dailyFact]);
 return <div className="app-shell"><LeafField/><aside className="sidebar"><div className="brand"><div className="brand-mark">🧬</div><div><strong>Biology-Study</strong><span>Learn • Test • Master</span></div></div><nav aria-label="Biology study sections">{sections.map(section=><button key={section} className={active===section?"nav-item active":"nav-item"} onClick={()=>setActive(section)}><span className="nav-icon" aria-hidden="true">{icons[section]}</span><span>{section}</span></button>)}</nav><div className="sidebar-footer"><div className="level-card"><span>Study Level</span><strong>Level {Math.floor(progress.points/50)+1}</strong><div className="progress"><i style={{width:`${Math.min(100,(progress.points%50)*2)}%`}}/></div><small>{progress.points%50} / 50 points to next badge</small></div></div></aside><main className="main"><header className="topbar"><div><p className="eyebrow">🧬 {time.toLocaleDateString(undefined,{weekday:"long",month:"short",day:"numeric"})}</p><h1>{greeting}, Student.</h1></div><div className="header-actions"><span className="clock">{time.toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</span><button className="secondary-button fullscreen-site-button" onClick={toggleFullscreen} aria-label={isFullscreen?"Exit full screen":"Open full screen"}>{isFullscreen?"⛶ Exit Full Screen":"⛶ Full Site"}</button><button className="icon-button" onClick={()=>setDark(v=>!v)} aria-label="Toggle theme">{dark?"☀":"☾"}</button></div></header>{celebration&&<Celebration message={celebration}/>} {active==="Dashboard"&&<Dashboard progress={progress} onLesson={()=>setActive("Lesson")} onCAT={()=>setActive("CAT")} onRevision={()=>setActive("Revision")} />}{active==="Lesson"&&<Lesson onRead={(p)=>{completeTask(p,"Lesson completed! RAT unlocked.");setActive("RAT");}} onExit={()=>setActive("Dashboard")} />}{active==="RAT"&&<RAT onExit={()=>setActive("Dashboard")} onProgress={(p)=>completeTask(p,"RAT complete! Great work.")} onLesson={()=>setActive("Lesson")} />}{active==="CAT"&&<CAT onExit={()=>setActive("Dashboard")} onProgress={(p)=>completeTask(p,"CAT complete! Assessment recorded.")} />}{active==="Revision"&&<Revision onExit={()=>setActive("Dashboard")} onProgress={(p)=>completeTask(p,"Revision complete! Knowledge reinforced.")} />}{active==="Practice"&&<Practice onExit={()=>setActive("Dashboard")} onProgress={(p)=>completeTask(p,"Practice session complete!")} />}{active==="Analytics"&&<Analytics progress={progress} onRefresh={setProgress} />}{!["Dashboard","Lesson","RAT","CAT","Revision","Practice","Analytics"].includes(active)&&<ComingSoon section={active}/>}</main></div>;
}
function Dashboard({progress,onLesson,onCAT,onRevision}:{progress:StudyProgress;onLesson:()=>void;onCAT:()=>void;onRevision:()=>void}){
 const read=hasReadLessonToday(progress),ratDone=hasCompletedRATToday(progress),revision=progress.missedQuestionIds.length;
 return <div className="content"><section className="hero-grid"><div className="hero-card"><div><span className="badge">TODAY&apos;S STUDY PATH</span><h2>{ratDone?"RAT completed. Keep mastering your weak areas.":read?"Lesson complete. Take today&apos;s RAT.":"Lesson first. RAT second."}</h2><p>{ratDone?"Your scheduled RAT is complete for today. Review missed questions in Revision.":read?"The lesson has been completed. The RAT is now unlocked for today.":"The daily RAT stays locked until the lesson is completed."}</p></div><div className="result-actions">{!read&&!ratDone&&<button className="primary-button" onClick={onLesson}>TODAY&apos;S LESSON</button>}{read&&!ratDone&&<button className="primary-button" onClick={onLesson}>OPEN TODAY'S LESSON • TAKE RAT</button>}{ratDone&&<span className="badge success">RAT DONE FOR TODAY</span>} {revision>0&&<button className="secondary-button" onClick={onRevision}>Revision • {revision}</button>}</div></div><div className="streak-card"><span className="muted">Current streak</span><strong>{progress.streak} day{progress.streak===1?"":"s"}</strong><span>{progress.streak?"Keep studying today to protect your streak.":"Complete a study session today to begin."}</span></div></section><section className="stats-grid"><Stat label="Study points" value={String(progress.points)} detail="Points from completed RATs, CATs and revision only"/><Stat label="RATs completed" value={String(progress.attempts.filter(a=>a.type==="RAT").length)} detail="Once daily • 10 questions • 15 minutes"/><Stat label="CATs completed" value={String(progress.attempts.filter(a=>a.type==="CAT").length)} detail="After 3 consecutive daily RATs • 20 questions • 30 minutes"/><Stat label="Revision queue" value={String(revision)} detail="Missed questions to master"/></section><section className="dashboard-grid"><div className="panel"><div className="panel-heading"><div><span className="eyebrow">Daily engagement</span><h3>Fact of the Day</h3></div><span className="fact-tag">MEDICAL</span></div><p className="fact typing-fact">{typedFact}<span className="typing-caret" aria-hidden="true">▌</span></p><div className="fact-reference"><span>{dailyFact.source}</span><small>{dailyFact.reference}</small></div></div><div className="panel"><div className="panel-heading"><div><span className="eyebrow">Today&apos;s flow</span><h3>Study checklist</h3></div></div><Task title="1. TODAY&apos;S LESSON" meta={read?"Completed at 100%":"Required before RAT"} status={read?"Done":"Open"}/><Task title="2. TAKE RAT" meta={ratDone?"Completed today":read?"Unlocked after lesson":"Locked until lesson reaches 100%"} status={ratDone?"Done":read?"Ready":"Locked"}/><Task title="3. Revision" meta={revision?revision+" missed question"+(revision===1?"":"s")+" waiting":"No missed questions"} status={revision?"Review":"Clear"}/></div></section></div>;
}
function LeafField(){return <div className="leaf-field" aria-hidden="true">{Array.from({length:22},(_,index)=><span key={index} style={{"--leaf-x":`${(index*47)%103}%`,"--leaf-delay":`${(index*0.73)%8}s`,"--leaf-duration":`${8+(index%6)}s`,"--leaf-size":`${8+(index%7)}px`} as CSSProperties}/>)}</div>;}
function Stat({label,value,detail}:{label:string;value:string;detail:string}){return <div className="stat-card"><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>;}
function Task({title,meta,status}:{title:string;meta:string;status:string}){return <div className="task"><div><strong>{title}</strong><span>{meta}</span></div><b>{status}</b></div>;}
function Celebration({message}:{message:string}){return <div className="celebration-overlay" role="status" aria-live="polite"><div className="celebration-burst" aria-hidden="true">{["🧬","🧫","🧪","🔬","🧠","🌿","✨","🧬"].map((item,index)=><span key={index} style={{"--i":index} as CSSProperties}>{item}</span>)}</div><div className="celebration-card"><span className="celebration-icon">✓</span><span className="badge success">TASK COMPLETE</span><h2>Congratulations!</h2><p>{message}</p><small>Keep the chain alive. Every completed task moves your biology mastery forward.</small></div></div>;}
function ComingSoon({section}:{section:Section}){return <div className="content"><div className="empty-state"><span className="badge">🧬 NEXT MODULE</span><h2>{section}</h2><p>This study module is planned for the next build stage.</p><button className="primary-button" onClick={()=>window.scrollTo({top:0,behavior:"smooth"})}>{section==="Calendar"?"🗓️ Study Calendar":"⚙️ Study Settings"}</button></div></div>;}
export default App;