import { useEffect, useMemo, useState, type CSSProperties, type FormEvent } from "react";
import RAT from "./pages/RAT";
import CAT from "./pages/CAT";
import Revision from "./pages/Revision";
import Practice from "./pages/Practice";
import Lesson from "./pages/Lesson";
import Analytics from "./pages/Analytics";
import { getProgress, hasCompletedRATToday, hasReadLessonToday, replaceProgress, type StudyProgress } from "./data/progress";
import { getDailyFact } from "./data/commonKnowledge";
import { acceptCookieConsent, clearAccountStudyData, clearLocalAccount, createLocalAccount, getAccount, hasCookieConsent, hydrateRemoteProgress, hasRemoteSession, verifyLocalPassword, type LocalAccount } from "./data/account";

type Section="Dashboard"|"Lesson"|"RAT"|"CAT"|"Practice"|"Revision"|"Analytics"|"Calendar"|"Settings";
const sections:Section[]=["Dashboard","Lesson","RAT","CAT","Practice","Revision","Analytics","Calendar","Settings"];
const icons:Record<Section,string>={Dashboard:"⌂",Lesson:"01",RAT:"02",CAT:"03",Practice:"04",Revision:"05",Analytics:"06",Calendar:"07",Settings:"08"};

function App(){
 const [active,setActive]=useState<Section>("Dashboard"),[dark,setDark]=useState(true),[time,setTime]=useState(new Date()),[progress,setProgress]=useState<StudyProgress>(()=>getProgress()),[isFullscreen,setIsFullscreen]=useState(false),[celebration,setCelebration]=useState<string|null>(null);
 const [account,setAccount]=useState<LocalAccount|null>(()=>getAccount());
 const [authenticated,setAuthenticated]=useState(()=>sessionStorage.getItem("biology-study:authenticated")==="true");
 const [showOnboarding,setShowOnboarding]=useState(()=>!getAccount());
 const [cookieConsent,setCookieConsent]=useState(()=>hasCookieConsent());
 const [scrollProgress,setScrollProgress]=useState(0);
 useEffect(()=>{const timer=window.setInterval(()=>setTime(new Date()),1000);return()=>window.clearInterval(timer);},[]);\n useEffect(()=>{void (async()=>{if(!hasRemoteSession())return;const remote=await hydrateRemoteProgress();if(remote&&typeof remote==="object")setProgress(replaceProgress(remote as StudyProgress));})();},[]);
 useEffect(()=>{document.documentElement.dataset.theme=dark?"dark":"light";},[dark]);
 useEffect(()=>{
   const main=document.querySelector(".main");
   if(!main)return;
   const update=()=>{const max=main.scrollHeight-main.clientHeight;setScrollProgress(max>0?Math.min(100,(main.scrollTop/max)*100):0);};
   update(); main.addEventListener("scroll",update,{passive:true});
   window.addEventListener("resize",update);
   return()=>{main.removeEventListener("scroll",update);window.removeEventListener("resize",update);};
 },[active]);
 useEffect(()=>{const sync=()=>setIsFullscreen(Boolean(document.fullscreenElement));document.addEventListener("fullscreenchange",sync);return()=>document.removeEventListener("fullscreenchange",sync);},[]);
 const toggleFullscreen=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{}};
 const completeTask=(next:StudyProgress,message:string)=>{setProgress(next);setCelebration(message);window.setTimeout(()=>setCelebration(null),2800);};
 const greeting=useMemo(()=>{const h=time.getHours();return h<12?"Good Morning":h<18?"Good Afternoon":"Good Evening";},[time]);
 const dailyFact=useMemo(()=>getDailyFact(time),[time]);
 const [typedFact,setTypedFact]=useState("");
 useEffect(()=>{setTypedFact("");let index=0;const timer=window.setInterval(()=>{index+=1;setTypedFact(dailyFact.fact.slice(0,index));if(index>=dailyFact.fact.length)window.clearInterval(timer);},28);return()=>window.clearInterval(timer);},[dailyFact]);
 const finishOnboarding=async(name:string,password:string)=>{const created=await createLocalAccount(name,password);setAccount(created);setProgress(getProgress());sessionStorage.setItem("biology-study:authenticated","true");setAuthenticated(true);setShowOnboarding(false);};\n const signIn=async(username:string,password:string,remember:boolean)=>{const ok=await verifyLocalPassword(password,username);if(ok){setAccount(getAccount());setProgress(getProgress());sessionStorage.setItem("biology-study:authenticated","true");if(remember)localStorage.setItem("biology-study:remember-login","true");setAuthenticated(true);setShowOnboarding(false);}return ok;};
 const login=async(password:string,remember:boolean)=>{if(await verifyLocalPassword(password,account?.username)){if(remember)localStorage.setItem("biology-study:remember-login","true");sessionStorage.setItem("biology-study:authenticated","true");setAuthenticated(true);return true;}return false;};
 const logout=()=>{sessionStorage.removeItem("biology-study:authenticated");localStorage.removeItem("biology-study:remember-login");setAuthenticated(false);setActive("Dashboard");};
 const studentName=account?.studentName||"Student";
 if(account && !authenticated && localStorage.getItem("biology-study:remember-login")==="true"){sessionStorage.setItem("biology-study:authenticated","true");}
 const locked=Boolean(account && !authenticated && localStorage.getItem("biology-study:remember-login")!=="true");
 return <div className="app-shell"><LeafField/><aside className="sidebar"><div className="brand"><div className="brand-mark">🧬</div><div><strong>Biology-Study</strong><span>Learn • Test • Master</span></div></div><nav aria-label="Biology study sections">{sections.map(section=><button key={section} className={active===section?"nav-item active":"nav-item"} onClick={()=>setActive(section)}><span className="nav-icon" aria-hidden="true">{icons[section]}</span><span>{section}</span></button>)}</nav><div className="sidebar-footer"><div className="level-card"><span>Study Level</span><strong>Level {Math.floor(progress.points/50)+1}</strong><div className="progress"><i style={{width:`${Math.min(100,(progress.points%50)*2)}%`}}/></div><small>{progress.points%50} / 50 points to next badge</small></div></div></aside><main className="main"><header className="topbar"><div><p className="eyebrow">🧬 {time.toLocaleDateString(undefined,{weekday:"long",month:"short",day:"numeric"})}</p><h1>{greeting}, {studentName}.</h1><span className="student-username">@{account?.username||"student"}</span></div><div className="header-actions"><span className="clock">{time.toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</span><button className="secondary-button fullscreen-site-button" onClick={toggleFullscreen} aria-label={isFullscreen?"Exit full screen":"Open full screen"}>{isFullscreen?"⛶ Exit Full Screen":"⛶ Full Site"}</button><button className="icon-button" onClick={()=>setDark(v=>!v)} aria-label="Toggle theme">{dark?"☀":"☾"}</button></div></header>{celebration&&<Celebration message={celebration}/>} {active==="Dashboard"&&<Dashboard progress={progress} onLesson={()=>setActive("Lesson")} onCAT={()=>setActive("CAT")} onRevision={()=>setActive("Revision")} typedFact={typedFact} dailyFact={dailyFact} />}{active==="Lesson"&&<Lesson onRead={(p)=>{completeTask(p,"Lesson completed! RAT unlocked.");setActive("RAT");}} onExit={()=>setActive("Dashboard")} />}{active==="RAT"&&<RAT onExit={()=>setActive("Dashboard")} onProgress={(p)=>completeTask(p,"RAT complete! Great work.")} onLesson={()=>setActive("Lesson")} />}{active==="CAT"&&<CAT onExit={()=>setActive("Dashboard")} onProgress={(p)=>completeTask(p,"CAT complete! Assessment recorded.")} />}{active==="Revision"&&<Revision onExit={()=>setActive("Dashboard")} onProgress={(p)=>completeTask(p,"Revision complete! Knowledge reinforced.")} />}{active==="Practice"&&<Practice onExit={()=>setActive("Dashboard")} onProgress={(p)=>completeTask(p,"Practice session complete!")} />}{active==="Analytics"&&<Analytics progress={progress} onRefresh={setProgress} />}
{active==="Settings"&&<Settings account={account} onAccount={setAccount} onLogout={logout} onProgressReset={()=>setProgress(getProgress())} />}
{active==="Calendar"&&<ComingSoon section={active}/>}
<div className="scroll-progress-track" aria-hidden="true"><i style={{width:`${scrollProgress}%`}}/></div>
{showOnboarding&&<Onboarding onCreate={finishOnboarding} onLogin={signIn}/>} {locked&&<LoginOverlay studentName={studentName} username={account?.username||""} onLogin={login}/>}
{!cookieConsent&&<CookieBanner onAccept={()=>{acceptCookieConsent();setCookieConsent(true);}}/>}
</main></div>;
}
function Dashboard({progress,onLesson,onCAT,onRevision,typedFact,dailyFact}:{progress:StudyProgress;onLesson:()=>void;onCAT:()=>void;onRevision:()=>void;typedFact:string;dailyFact:ReturnType<typeof getDailyFact>}){
 const read=hasReadLessonToday(progress),ratDone=hasCompletedRATToday(progress),revision=progress.missedQuestionIds.length;
 return <div className="content"><section className="hero-grid"><div className="hero-card"><div><span className="badge">TODAY&apos;S STUDY PATH</span><h2>{ratDone?"RAT completed. Keep mastering your weak areas.":read?"Lesson complete. Take today&apos;s RAT.":"Lesson first. RAT second."}</h2><p>{ratDone?"Your scheduled RAT is complete for today. Review missed questions in Revision.":read?"The lesson has been completed. The RAT is now unlocked for today.":"The daily RAT stays locked until the lesson is completed."}</p></div><div className="result-actions">{!read&&!ratDone&&<button className="primary-button" onClick={onLesson}>TODAY&apos;S LESSON</button>}{read&&!ratDone&&<button className="primary-button" onClick={onLesson}>OPEN TODAY'S LESSON • TAKE RAT</button>}{ratDone&&<span className="badge success">RAT DONE FOR TODAY</span>} {revision>0&&<button className="secondary-button" onClick={onRevision}>Revision • {revision}</button>}</div></div><div className="streak-card"><span className="muted">Current streak</span><strong>{progress.streak} day{progress.streak===1?"":"s"}</strong><span>{progress.streak?"Keep studying today to protect your streak.":"Complete a study session today to begin."}</span></div></section><section className="stats-grid"><Stat label="Study points" value={String(progress.points)} detail="Points from completed RATs, CATs and revision only"/><Stat label="RATs completed" value={String(progress.attempts.filter(a=>a.type==="RAT").length)} detail="Once daily • 10 questions • 15 minutes"/><Stat label="CATs completed" value={String(progress.attempts.filter(a=>a.type==="CAT").length)} detail="After 3 consecutive daily RATs • 20 questions • 30 minutes"/><Stat label="Revision queue" value={String(revision)} detail="Missed questions to master"/></section><section className="dashboard-grid"><div className="panel"><div className="panel-heading"><div><span className="eyebrow">Daily engagement</span><h3>Fact of the Day</h3></div><span className="fact-tag">MEDICAL</span></div><p className="fact typing-fact">{typedFact}<span className="typing-caret" aria-hidden="true">▌</span></p><div className="fact-reference"><span>{dailyFact.source}</span><small>{dailyFact.reference}</small></div></div><div className="panel"><div className="panel-heading"><div><span className="eyebrow">Today&apos;s flow</span><h3>Study checklist</h3></div></div><Task title="1. TODAY&apos;S LESSON" meta={read?"Completed at 100%":"Required before RAT"} status={read?"Done":"Open"}/><Task title="2. TAKE RAT" meta={ratDone?"Completed today":read?"Unlocked after lesson":"Locked until lesson reaches 100%"} status={ratDone?"Done":read?"Ready":"Locked"}/><Task title="3. Revision" meta={revision?revision+" missed question"+(revision===1?"":"s")+" waiting":"No missed questions"} status={revision?"Review":"Clear"}/></div></section></div>;
}
function LeafField(){return <div className="leaf-field" aria-hidden="true">{Array.from({length:22},(_,index)=><span key={index} style={{"--leaf-x":`${(index*47)%103}%`,"--leaf-delay":`${(index*0.73)%8}s`,"--leaf-duration":`${8+(index%6)}s`,"--leaf-size":`${8+(index%7)}px`} as CSSProperties}/>)}</div>;}
function Stat({label,value,detail}:{label:string;value:string;detail:string}){return <div className="stat-card"><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>;}
function Task({title,meta,status}:{title:string;meta:string;status:string}){return <div className="task"><div><strong>{title}</strong><span>{meta}</span></div><b>{status}</b></div>;}
function Celebration({message}:{message:string}){return <div className="celebration-overlay" role="status" aria-live="polite"><div className="celebration-burst" aria-hidden="true">{["🧬","🧫","🧪","🔬","🧠","🌿","✨","🧬"].map((item,index)=><span key={index} style={{"--i":index} as CSSProperties}>{item}</span>)}</div><div className="celebration-card"><span className="celebration-icon">✓</span><span className="badge success">TASK COMPLETE</span><h2>Congratulations!</h2><p>{message}</p><small>Keep the chain alive. Every completed task moves your biology mastery forward.</small></div></div>;}
function Settings({account,onAccount,onLogout,onProgressReset}:{account:LocalAccount|null;onAccount:(account:LocalAccount|null)=>void;onLogout:()=>void;onProgressReset:()=>void}){
 const [nodes,setNodes]=useState<string[]>(()=>{try{return JSON.parse(localStorage.getItem("biology-study:nodes")||"[]") as string[];}catch{return [];}});
 const [node,setNode]=useState(""); const [queue,setQueue]=useState<string[]>(()=>{try{return JSON.parse(localStorage.getItem("biology-study:validation-queue")||"[]") as string[];}catch{return [];}});
 const [confirmAction,setConfirmAction]=useState<"reset-progress"|"delete-account"|null>(null); const [password,setPassword]=useState(""); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
 const addNode=()=>{const value=node.trim();if(!value)return;const next=[...nodes,value];setNodes(next);localStorage.setItem("biology-study:nodes",JSON.stringify(next));setNode("");};
 const removeNode=(index:number)=>{const next=nodes.filter((_,i)=>i!==index);setNodes(next);localStorage.setItem("biology-study:nodes",JSON.stringify(next));};
 const addValidation=()=>{if(!nodes.length)return;const next=Array.from(new Set([...queue,nodes[nodes.length-1]]));setQueue(next);localStorage.setItem("biology-study:validation-queue",JSON.stringify(next));};
 const clearQueue=()=>{setQueue([]);localStorage.removeItem("biology-study:validation-queue");};
 const openConfirm=(action:"reset-progress"|"delete-account")=>{setConfirmAction(action);setPassword("");setError("");};
 const closeConfirm=()=>{if(busy)return;setConfirmAction(null);setPassword("");setError("");};
 const confirmDestructiveAction=async()=>{
   if(!account)return; setError(""); setBusy(true);
   try{
     if(!(await verifyLocalPassword(password))){setError("Incorrect password. The action was not completed.");return;}
     if(confirmAction==="reset-progress"){clearAccountStudyData(account.id);onProgressReset();setNodes([]);setQueue([]);closeConfirm();}
     else if(confirmAction==="delete-account"){clearAccountStudyData(account.id);clearLocalAccount();sessionStorage.removeItem("biology-study:authenticated");localStorage.removeItem("biology-study:remember-login");onAccount(null);closeConfirm();window.location.reload();}
   }finally{setBusy(false);}
 };
 return <div className="content"><div className="settings-header"><span className="badge">SYSTEM</span><h2>Study Settings</h2><p>Manage your local student profile, study nodes and validation queue.</p></div>
 <section className="settings-grid"><div className="panel settings-card"><span className="eyebrow">Student account</span><h3>{account?.studentName||"No account"}</h3><p className="settings-note">Username: <strong>{account?.username||"—"}</strong></p><p className="settings-note">With server authentication enabled, your password is verified on the backend and never stored in the browser.</p><div className="result-actions"><button className="secondary-button" onClick={onLogout}>Log out</button><button className="secondary-button danger-button" onClick={()=>openConfirm("delete-account")}>Delete account</button><button className="secondary-button danger-button" onClick={()=>openConfirm("reset-progress")}>Reset progress</button></div></div>
 <div className="panel settings-card"><span className="eyebrow">Node management</span><h3>Study Nodes</h3><div className="node-add"><input value={node} onChange={e=>setNode(e.target.value)} onKeyDown={e=>e.key==="Enter"&&addNode()} placeholder="e.g. Cell Biology" aria-label="New study node"/><button className="primary-button" onClick={addNode}>Add Node</button></div><div className="node-list">{nodes.length?nodes.map((item,i)=><div className="node-row" key={item+i}><span>{item}</span><button className="icon-button" onClick={()=>removeNode(i)} aria-label={"Remove "+item}>×</button></div>):<small>No study nodes created yet.</small>}</div></div>
 <div className="panel settings-card"><span className="eyebrow">Validating queue</span><h3>{queue.length} item{queue.length===1?"":"s"} waiting</h3><p className="settings-note">Use this local queue to flag study nodes for content checking before release.</p><div className="validation-list">{queue.length?queue.map((item,i)=><div className="validation-row" key={item+i}><span>{item}</span><b>Pending</b></div>):<small>Validation queue is clear.</small>}</div><div className="result-actions"><button className="secondary-button" onClick={addValidation} disabled={!nodes.length}>Queue latest node</button><button className="secondary-button" onClick={clearQueue} disabled={!queue.length}>Clear queue</button></div></div></section>
 {confirmAction&&<div className="confirm-overlay" role="dialog" aria-modal="true" aria-labelledby="confirm-title"><div className="confirm-card"><span className="badge danger-badge">{confirmAction==="delete-account"?"DANGER":"CONFIRM ACTION"}</span><h2 id="confirm-title">{confirmAction==="delete-account"?"Delete your account?":"Reset all study progress?"}</h2><p>{confirmAction==="delete-account"?"This permanently removes this local account and its study data from this browser. This cannot be undone.":"This removes your points, streak, RAT/CAT/Revision/Practice history, lesson history, active assessments, study nodes and validation queue. Your account remains."}</p><label>Enter your password to continue<input value={password} onChange={e=>setPassword(e.target.value)} type="password" autoFocus required placeholder="Current password" onKeyDown={e=>{if(e.key==="Enter")void confirmDestructiveAction();}}/></label>{error&&<div className="form-error">{error}</div>}<div className="confirm-actions"><button type="button" className="secondary-button" onClick={closeConfirm} disabled={busy}>Cancel</button><button type="button" className="primary-button danger-action" onClick={()=>void confirmDestructiveAction()} disabled={busy||!password}>{busy?"Verifying...":confirmAction==="delete-account"?"Delete account":"Reset progress"}</button></div><small>Password verification is required. Nothing is changed when the password is incorrect.</small></div></div>}
 </div>;
}
function Onboarding({onCreate,onLogin}:{onCreate:(name:string,password:string)=>Promise<void>;onLogin:(username:string,password:string,remember:boolean)=>Promise<boolean>}) {
 const [mode,setMode]=useState<"create"|"login">("create"); const [name,setName]=useState(""); const [username,setUsername]=useState(""); const [password,setPassword]=useState(""); const [confirm,setConfirm]=useState(""); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
 const submit=async(e:FormEvent)=>{e.preventDefault();setError("");if(password.length<6){setError("Use at least 6 characters for your password.");return;}if(mode==="create"&&password!==confirm){setError("Passwords do not match.");return;}setBusy(true);try{if(mode==="create")await onCreate(name,password);else if(!(await onLogin(username,password,true)))setError("Invalid username or password.");}catch(err){setError(err instanceof Error?err.message:"Could not complete authentication.");}finally{setBusy(false);}};
 return <div className="onboarding-overlay"><form className="onboarding-card" onSubmit={submit}><span className="badge">{mode==="create"?"FIRST VISIT":"SIGN IN"}</span><h2>{mode==="create"?"Set up your Biology-Study profile":"Sign in to Biology-Study"}</h2><p>{mode==="create"?"Create an account that will sync across your devices.":"Use the same username and password you use on your other device."}</p>{mode==="create"?<label>Student name<input value={name} onChange={e=>setName(e.target.value)} autoFocus required placeholder="Your full student name"/></label>:<label>Username<input value={username} onChange={e=>setUsername(e.target.value)} autoFocus required placeholder="Your username"/></label>}<label>Password<input value={password} onChange={e=>setPassword(e.target.value)} type="password" minLength={6} required placeholder="At least 6 characters"/></label>{mode==="create"&&<label>Confirm password<input value={confirm} onChange={e=>setConfirm(e.target.value)} type="password" minLength={6} required placeholder="Repeat your password"/></label>}{error&&<div className="form-error">{error}</div>}<button className="primary-button" disabled={busy}>{busy?(mode==="create"?"Creating account...":"Signing in..."):(mode==="create"?"Create account":"Sign in")}</button><button type="button" className="secondary-button" onClick={()=>{setMode(mode==="create"?"login":"create");setError("");}}>{mode==="create"?"Already have an account? Sign in":"Need an account? Create one"}</button><small>Server authentication keeps the account and progress in the cloud when the backend is configured.</small></form></div>;
}
function CookieBanner({onAccept}:{onAccept:()=>void}){
 return <div className="cookie-banner"><div><strong>Cookies & local storage</strong><p>Biology-Study uses a small essential cookie to remember your cookie choice, plus local browser storage for your study progress and account profile.</p></div><button className="primary-button" onClick={onAccept}>Accept</button></div>;
}
function LoginOverlay({studentName,username,onLogin}:{studentName:string;username:string;onLogin:(password:string,remember:boolean)=>Promise<boolean>}) {
 const [password,setPassword]=useState("");const [remember,setRemember]=useState(true);const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 const submit=async(e:FormEvent)=>{e.preventDefault();setError("");setBusy(true);try{if(!(await onLogin(password,remember)))setError("Incorrect password.");else setPassword("");}finally{setBusy(false);}};
 return <div className="onboarding-overlay"><form className="onboarding-card" onSubmit={submit}><span className="badge">WELCOME BACK</span><h2>Sign in, {studentName}</h2><p>{username?"Username: "+username:"Enter your account password"}.</p><label>Password<input value={password} onChange={e=>setPassword(e.target.value)} type="password" autoFocus required placeholder="Your password"/></label><label className="remember-row"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/><span>Remember me on this browser</span></label>{error&&<div className="form-error">{error}</div>}<button className="primary-button" disabled={busy}>{busy?"Checking...":"Sign in"}</button><small>Your session is protected by the Biology-Study authentication server.</small></form></div>;
}
function ComingSoon({section}:{section:Section}){return <div className="content"><div className="empty-state"><span className="badge">🧬 NEXT MODULE</span><h2>{section}</h2><p>This study module is planned for the next build stage.</p><button className="primary-button" onClick={()=>window.scrollTo({top:0,behavior:"smooth"})}>{section==="Calendar"?"🗓️ Study Calendar":"⚙️ Study Settings"}</button></div></div>;}
export default App;