import { useEffect, useMemo, useState } from "react";
import RAT from "./pages/RAT";
import CAT from "./pages/CAT";
import { getProgress, type StudyProgress } from "./data/progress";

type Section = "Dashboard" | "RAT" | "CAT" | "Practice" | "Revision" | "Analytics" | "Calendar" | "Settings";
const sections: Section[] = ["Dashboard", "RAT", "CAT", "Practice", "Revision", "Analytics", "Calendar", "Settings"];
const icons: Record<Section, string> = { Dashboard: "⌂", RAT: "✓", CAT: "◈", Practice: "◎", Revision: "↻", Analytics: "▥", Calendar: "▣", Settings: "⚙" };

function App() {
  const [active, setActive] = useState<Section>("Dashboard"); const [dark, setDark] = useState(true); const [time, setTime] = useState(new Date()); const [progress, setProgress] = useState<StudyProgress>(() => getProgress());
  useEffect(() => { const timer = window.setInterval(() => setTime(new Date()), 1000); return () => window.clearInterval(timer); }, []);
  useEffect(() => { document.documentElement.dataset.theme = dark ? "dark" : "light"; }, [dark]);
  const greeting = useMemo(() => { const hour = time.getHours(); if (hour < 12) return "Good Morning"; if (hour < 17) return "Good Afternoon"; if (hour < 21) return "Good Evening"; return "Good Night"; }, [time]);
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">B</div><div><strong>Biology-Study</strong><span>Learn. Test. Master.</span></div></div><nav>{sections.map(section => <button key={section} className={active === section ? "nav-item active" : "nav-item"} onClick={() => setActive(section)}><span className="nav-icon">{icons[section]}</span><span>{section}</span></button>)}</nav><div className="sidebar-footer"><div className="level-card"><span>Study Level</span><strong>Level {Math.floor(progress.points / 50) + 1}</strong><div className="progress"><i style={{ width: `${Math.min(100, (progress.points % 50) * 2)}%` }} /></div><small>{progress.points % 50} / 50 points to next badge</small></div></div></aside><main className="main"><header className="topbar"><div><p className="eyebrow">{time.toLocaleDateString(undefined, { weekday: "long", month: "short", day: "numeric" })}</p><h1>{greeting}, Student.</h1></div><div className="header-actions"><span className="clock">{time.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</span><button className="icon-button" onClick={() => setDark(value => !value)} aria-label="Toggle theme">{dark ? "☀" : "☾"}</button></div></header>{active === "Dashboard" && <Dashboard progress={progress} onStart={() => setActive("RAT")} onCAT={() => setActive("CAT")} />}{active === "RAT" && <RAT onExit={() => setActive("Dashboard")} onProgress={setProgress} />}{active === "CAT" && <CAT onExit={() => setActive("Dashboard")} onProgress={setProgress} />}{!["Dashboard", "RAT", "CAT"].includes(active) && <ComingSoon section={active} />}</main></div>;
}
function Dashboard({ progress, onStart, onCAT }: { progress: StudyProgress; onStart: () => void; onCAT: () => void }) {
  const latest = progress.attempts[0]; const latestCAT = progress.attempts.find(a => a.type === "CAT");
  return <div className="content"><section className="hero-grid"><div className="hero-card"><div><span className="badge">BIOLOGY • STUDY HUB</span><h2>Build your knowledge one question at a time.</h2><p>Daily RATs, scheduled CATs, revision, analytics and a growing biology question bank.</p></div><div className="result-actions"><button className="primary-button" onClick={onStart}>Start today's RAT</button><button className="secondary-button" onClick={onCAT}>Open CAT</button></div></div><div className="streak-card"><span className="muted">Current streak</span><strong>{progress.streak} day{progress.streak === 1 ? "" : "s"}</strong><span>{progress.streak ? "Keep studying today to protect your streak." : "Complete a study session today to begin."}</span></div></section><section className="stats-grid"><Stat label="Study points" value={String(progress.points)} detail="Points from completed assessments" /><Stat label="RATs completed" value={String(progress.attempts.filter(a => a.type === "RAT").length)} detail="10 questions • 15 minutes" /><Stat label="CATs completed" value={String(progress.attempts.filter(a => a.type === "CAT").length)} detail="20 questions • 30 minutes" /><Stat label="Latest accuracy" value={latest ? `${latest.accuracy}%` : "0%"} detail={latest ? `${latest.type} • ${latest.passed ? "Passed" : "Review recommended"}` : "Complete your first assessment"} /></section><section className="dashboard-grid"><div className="panel"><div className="panel-heading"><div><span className="eyebrow">Daily engagement</span><h3>Fact of the Day</h3></div><span className="fact-tag">MEDICAL</span></div><p className="fact">The human heart has four chambers that work together to maintain continuous blood circulation.</p><small>Reference-backed facts will be connected to the study content layer.</small></div><div className="panel"><div className="panel-heading"><div><span className="eyebrow">Progress</span><h3>Recent activity</h3></div></div>{latest ? <Task title={`${latest.type} attempt`} meta={new Date(latest.completedAt).toLocaleString()} status={latest.passed ? "Passed" : "Review"} /> : <Task title="No attempts yet" meta="Your completed assessments will appear here." status="Ready" />}{latestCAT && <Task title="Latest CAT" meta={new Date(latestCAT.completedAt).toLocaleString()} status={latestCAT.passed ? "Passed" : "Review"} />}</div></section></div>;
}
function Stat({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="stat-card"><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>; }
function Task({ title, meta, status }: { title: string; meta: string; status: string }) { return <div className="task"><div><strong>{title}</strong><span>{meta}</span></div><b>{status}</b></div>; }
function ComingSoon({ section }: { section: Section }) { return <div className="content"><div className="empty-state"><span className="badge">NEXT MODULE</span><h2>{section}</h2><p>This module is planned for the next build stage. The assessment engine now supports persistent RATs and CATs with local progress tracking.</p></div></div>; }
export default App;